lib: system: fix missing metal_yield API for generic systems.
The metal_yield API needs also to be declared for the baremetal systems.
This fix build issue in Open-amp for generic system:

/github/workspace/open-amp/lib/rpmsg/rpmsg_virtio.c:275:17:
error: implicit declaration of function 'metal_yield'
275 |                 metal_yield();
    |                 ^~~~~~~~~~~

Signed-off-by: Arnaud Pouliquen <arnaud.pouliquen@foss.st.com>