cache.h: fix compile error of unused parameter
error: unused parameter ‘addr’ [-Werror=unused-parameter]
   25 | static inline void __metal_cache_flush(void *addr, unsigned int len)
      |                                        ~~~~~~^~~~
error: unused parameter ‘len’ [-Werror=unused-parameter]
   25 | static inline void __metal_cache_flush(void *addr, unsigned int len)
      |                                                    ~~~~~~~~~~~~~^~~

Signed-off-by: Yongrong Wang <wangyongrong@xiaomi.com>